### DISCUSSION TITLE
Data Directory

### DISCUSSION THREAD

**Discussion by Bovive** [hay-kot/homebox#332] [Q&A] [answered]
Hello,

Is it possible to set the data directory outside of Docker using the docker compose file? Setting the "home-box-data" directory did not seem to work. Thanks very much!

**Comment by hay-kot** [comment, marked as answer]
That should work, it's how we setup the development environment.

Can you provide any more details on how you're deploying? Os, commands, and non-secret env settings?

**Reply by Bovive** [reply]
Sure thing. I'm running Ubuntu 22.04 and Docker Desktop. I set the drive under my Docker Desktop resource folder and the same pathing has worked for other containers. I also made sure that the directory ownership and permissions are correct. Perhaps I am entering it in an incorrect format, I am certainly no Docker expert. 

### Here is my docker-compose file:

```yaml
version: "3.4"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=50
    - HBOX_OPTIONS_ALLOW_REGISTRATION=true
    volumes:
      - homebox-data:/Storage/Homebox/data/
    ports:
      - 3122:7745

volumes:
   homebox-data:
     driver: local`
```

### When I inspect the container this is what I see for mounts:

Mounts
/STORAGE/HOMEBOX/DATA
/var/lib/docker/volumes/homebox_homebox-data/_data


/DATA
/var/lib/docker/volumes/ad4801e5015240a49ff884e458ac3b0d7a9ac67489abfacc0bd867fdccbce1fa/_data

Thanks!

**Reply by hay-kot** [reply]
Ahhhhh I see, you've got your mounts set incorrectly. I'm assuming you want to mount the `/Storage/Homebox/data` directory to the containers data directory. This is probably closer to what you want

```yaml
version: "3.4"

services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: always
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=50
    - HBOX_OPTIONS_ALLOW_REGISTRATION=true
    volumes:
      - /Storage/Homebox/data/:/data/
    ports:
      - 3122:7745

```

See this for an example

![CleanShot 2023-03-03 at 07 53 40@2x](https://user-images.githubusercontent.com/64056131/222780256-05b88db7-3f96-49dc-9b78-70208bc6ce01.png)
