### DISCUSSION TITLE
Where is the log file supposed to be?

### DISCUSSION THREAD

**Discussion by xX-MrN0b0dy-Xx** [hay-kot/homebox#878] [Q&A]
Hello to everyone. This project is wonderful but there is a thing that I don't understand. Given that in the guide only the path `/data` is exposed, I imaged that an eventual log file would appear there or worse comes worst in the usual path `/var/log`. I don't know if it is not expected or if a problem that I specifically have... but is neither in `/data` nor in `/var/log` inside the container. I tried to look around inside the running container but it doesn't seem to be anywhere.

To be clear, here my compose:
```yaml
services:
# Security: to be implemented (maybe service provide log and fail2ban jail, implemented in fail2ban)
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    restart: always
    environment:
      HBOX_LOG_LEVEL: info
      HBOX_LOG_FORMAT: text
      HBOX_WEB_MAX_UPLOAD_SIZE: 10
      HBOX_OPTIONS_ALLOW_REGISTRATION: false
    volumes:
      - /my/path:/data/
    ports:
      - 31123:7745
```
