### ISSUE TITLE
Container Reverse Proxy Support/Instructions

### ISSUE THREAD

**Issue by madtempest** [hay-kot/homebox#386]
### What is the problem you are trying to solve with this feature?

It would appear that Homebox is not able to be reverse proxied when containerised. The test use case has been Nginx, but I suspect Caddy/Apache etc are also unable to do this.

Example code from the Nginx container:

    location / {
        proxy_pass http://hostname:3100;
        proxy_redirect          off;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        Accept-Encoding gzip;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection upgrade;
  }

Note that the internal container IP for the Homebox container and the Nginx container is the same. Attempting to use homebox:7745 for the proxypass variable does not work, nor does publishing the port to 3100:7745 and proxying the host:3100.

There is nothing in the Nginx access or error logs.

Reading your code, it looks like the front-end is running on Swagger. I've done some searches via Google on how to proxy Swagger and come across this https://stackoverflow.com/questions/75534221/swagger-ui-with-nginx-reverse-proxy however reading the log file I'm not sure this kind of redirect approach will work.

### What is the solution you are proposing?

Instructions/documentation and or development changes to support reverse proxying of the Homebox web UI.

### What alternatives have you considered?

I've tried changing the exposed port. I have considered changing the environment variables HBOX_SWAGGER_HOST and HBOX_SWAGGER_SCHEMA however in my docker-compose.yml neither of these variable are set and it still appears that Swagger is running based on the log file and the failure of Nginx to reverse proxy the data.

Also, doing a telnet and an ncat to the container on 7745 from the nginx container does not work either. Doing a GET via telnet generates a http 400 error.

I do recognise that there is already https support available using the HBOX_SWAGGER_SCHEMA environment variable however the documentation is unclear on how or where certificates can be replaced with self-signed or internal PKI.

### Additional context

I feel that adding reverse proxy support will enhance the security of the product and may even assist with some of the other SSO/authentication login requests.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
I have this working fine with Traefik, and haven't heard of any issues yet, so I'm guessing this is more an issue with your setup.

Can you post more about your deployment? Docker-compose and network setup would be helpful.

Also, Swagger is the API documentation platform, and is currently not really used in production, you can safely ignore those variables, theyve actually been removed the main branch.

**Comment by madtempest** [comment]
I figured it should be pretty straight forward too, which is why I'm confused because my docker-compose is pretty vanilla.

docker-compose.yml

```
version: "3.9"
networks:
  fortune_docker_apps:
    name: fortune_docker_apps
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.6.0/24

services:
#revproxy
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Perth
    volumes:
      - ./nginx:/config
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      fortune_docker_apps:
        ipv4_address: 172.28.6.254

  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
      - HBOX_OPTIONS_ALLOW_REGISTRATION=true
    volumes:
      - ./homebox:/data/
    ports:
      - 3100:7745
    networks:
      fortune_docker_apps:
        ipv4_address: 172.28.6.122
```


nginx vhost conf

```
server {
        listen 80;
        server_name homebox.fortune.internal;
        return 301 https://homebox.fortune.internalt$request_uri;
}

server {
        listen 443 ssl;
        server_name homebox.fortune.internal;
        ssl_certificate /config/keys/homebox.fortune.internal.crt;
        ssl_certificate_key /config/keys/homebox.fortune.internal.pem;
        ssl_prefer_server_ciphers on;

    #client_max_body_size 0;

    location / {
        proxy_pass http://fortune.internal:3100;
        proxy_redirect          off;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        Accept-Encoding gzip;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection upgrade;
  }
}
```

I've also tried the proxy_pass set to http://172.28.6.122:7745 and http://172.28.6.122.
