### ISSUE TITLE
Homebox is slow and keeps logging out in few minutes

### ISSUE THREAD

**Issue by Flashky** [hay-kot/homebox#525]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Version: v0.9.2 ~ Build: 21ad5a32c11eb9a7d6ff7332b3d9c91786673339

### What is the issue you are experiencing?

I try to add a few items, and it is very slow adding and updating. Sometimes it just logs out and I need to reenter my credentials.

### How can the maintainer reproduce the issue?

Just deploy, register with a new user, login and try to add a few items.

### Deployment

Docker (Synology)

### Deployment Details

I deployed with docker-compose on Synology:

```yaml
version: '3.8'
services:
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    restart: unless-stopped
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    - TZ=Europe/Madrid
    volumes:
      - /volume1/docker/homebox:/data/
    ports:
      - 3100:7745
```
