### ISSUE TITLE
Fields gets overwritten with wrong data after editing multiple assets in a row

### ISSUE THREAD

**Issue by concr** [hay-kot/homebox#548]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

Version: v0.9.2 ~ Build: 21ad5a32c11eb9a7d6ff7332b3d9c91786673339

### What is the issue you are experiencing?

If you edit one asset, go back to the home dashboard, edit another asset. Now you see some fields from the asset before. Like "Notes", "Purchase Date", "Warranty Expires". If you safe, the field gets overwritten with the values from the asset before.

### How can the maintainer reproduce the issue?

Prerequisites: At least two added assets

1. Login to HomeBox
2. From the home dashboard click on of the assets from the "Recently Added" list
3. Click "Edit" (you don't have to change / edit anything)
4. Click "Save"
5. Click "Home"
6. Select another asset from the "Recently Added" list
7. Click "Edit"
8. Now you see (at least) the fields "Notes", "Purchase Date" and "Warranty Expires" from the asset before.
9. If you click "Save" (at least) the value from the field "Notes" from the asset before overwrites the asset you're editing right now.

Workaround:

Between step 5 and 6 you have to refresh / reload the page. So back on the home dashboard just refresh / reload the page and then select another asset.

### Deployment

Docker (Linux)

### Deployment Details

```
version: "3.8"

services:
  app:
    image: "ghcr.io/hay-kot/homebox:latest"
    container_name: "homebox_app"
    labels:
      - "containermon.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.homebox-ui.rule=Host(`inventory.foo.bar`)"
      - "traefik.http.routers.homebox-ui.tls.certresolver=leresolver"
      - "traefik.http.routers.homebox-ui.entrypoints=websecure"
      - "traefik.http.routers.homebox-ui.middlewares=secure-headers@file,internal-ips-only@file"
      - "traefik.http.routers.homebox-ui.service=homebox"
      - "traefik.http.services.homebox.loadbalancer.server.port=7745"
    environment:
      - "HBOX_LOG_LEVEL=info"
      - "HBOX_LOG_FORMAT=text"
      - "HBOX_WEB_MAX_UPLOAD_SIZE=10"
      - "HBOX_OPTIONS_ALLOW_REGISTRATION=false"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./volumes/homebox/data:/data:rw"
    networks:
      - "proxy-network"
    restart: always

networks:
  proxy-network:
    external: true
```
