### ISSUE TITLE
docker-compose.yml lists deprecated version tag for Docker v2

### ISSUE THREAD

**Issue by CollapsingStar** [hay-kot/homebox#901]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### Homebox Version

0.10.3

### What is the issue you are experiencing?

The Docker Compose v2 "version: x.x" key/value pair is obsolete according to Docker's spec:

https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements

I believe the change to the docker-compose.yml (and corresponding setup docs here https://hay-kot.github.io/homebox/quick-start/) should be the following:

Before:

```
version: "3.4"

services:
  homebox:
    image: homebox
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - COMMIT=head
        - BUILD_TIME=0001-01-01T00:00:00Z
    ports:
      - 3100:7745
 ```

After:
```
services:
  homebox:
    image: homebox
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - COMMIT=head
        - BUILD_TIME=0001-01-01T00:00:00Z
    ports:
      - 3100:7745
 ```

### How can the maintainer reproduce the issue?

Reference the Docker setup docs and docker-compose.yml file when setting up a Docker container for the first time.

### Deployment

Docker (Linux)

### Deployment Details

N/A
